@isTest
private class TestVerifyQuoteApproval  {    
    static testMethod void myUnitTest() {

        Test.startTest();

        Test.stopTest();        

    }


}









/********************************************************************************************************************
* Project Name................: GOA                                                                                 *
* File........................: VerifyQuoteApproval.class                                                           *
* Version.....................: 1.0                                                                                 *
* Created by..................: eugenebasianomutya@gmail.com                                                        *
* Created Date................: 9/15/2015                                                                           *                                       
* Description.................: For case # 03931608 - This class retrieves Approvers for the quote.                 *
*                               It identifies whethere the quote being created will go through approval process.    *
*                               Once identified, it also provide who will be the approvers.                         *
*                                                                                                                   *   
********************************************************************************************************************/